# -*- coding: utf-8 -*-
"""calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15dPmILqaV47qWsWnU6PoG8WTl2Y8gw8m
"""

print("Simple calculator")
print("operations:+,-,*,/,^")

num1=float(input("Enter the number 1:"))
num2=float(input("Enter the number 2:"))

op=input("Enter the operation:")

if op=="+":
    print("Result is:",num1+num2)
elif op=="-":
    print("Result is:",num1-num2)
elif op=="*":
    print("Result is:",num1*num2)
elif op=="/":
  if num2!=0:
    print("Result is:",num1/num2)
  else:
    print("cannot divide by 0")
elif op=="^":
    print("Result is:",num1**num2)
else:
  print("Invalid operation")